kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  commands:
  - cd cli
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -e .
  - cd ..
  - make
  - ./drone-deploy new foobar
  - pytest --cov-config=.coveragerc --cov=cli -vv cli/tests/

---
# kine: pipeline
# name: linux-cli-build

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: linux-cli-build
#   image: python:3.7-alpine
#   commands:
#   - cd cli
#   - pip install --upgrade pip setuptools
#   - pip install -r requirements.txt
#   - pip install -e .
#   - pyinstaller drone-deploy.spec --hidden-import=configparser
#   - 

# when:
#   branch:
#   - develop
