kind: pipeline
name: default

clone:
  depth: 1

steps:
- name: test-x86_64-linux
  image: python:3.7
  environment:
    EDITOR: vim
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  commands:
  - pip install --upgrade pip setuptools
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make coverage

volumes:
- name: terraform
  host:
    path: /usr/local/bin/terraform

trigger:
  branch:
  - master
  - develop
  event:
  - push

---
kind: pipeline
name: release-linux

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - export DRONE_TAG=$DRONE_TAG
  - export DRONE_REPO_LINK=$DRONE_REPO_LINK
  - git clone -b $DRONE_TAG --depth 1 $DRONE_REPO_LINK

- name: release-x86_64-linux
  image: python:3.7
  commands:
  - cd drone-deploy
  - . cli/venv/bin/activate
  - make test
  - make release
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: repo_api_key
    files: drone-deploy/cli/dist/drone-deploy.x86_64-linux.tar.gz

volumes:
- name: terraform
  host:
    path: /usr/local/bin/terraform


trigger:
  event:
  - tag

---
# https://github.com/drone-runners/drone-runner-exec
kind: pipeline
type: exec
name: os-x

platform:
  os: darwin
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
  - export DRONE_TAG=$DRONE_TAG
  - export DRONE_REPO_LINK=$DRONE_REPO_LINK
  - git clone -b '$DRONE_TAG' --depth 1 $DRONE_REPO_LINK
  - cd drone-deploy

- name: test-x86_64-osx
  # ensure a recent version of git is installed on osx runner host
  environment:
    EDITOR: vim
    PATH: /usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH
    GITHUB_API_TOKEN:
      from_secret: repo_api_key
  commands:
  # ensure homebrew and terraform v0.11.14 are installed on osx runner host
  # also, we have to temporarily reinstall python because of bug:
  # https://discourse.brew.sh/t/pip-install-upgrade-pip-breaks-pip-when-installed-with-homebrew/5338
  - brew reinstall python
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make test

- name: publish-osx
  environment:
    PATH: /usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH
    GITHUB_API_TOKEN:
      from_secret: repo_api_key
  commands:
  - . cli/venv/bin/activate
  - make release

trigger:
  event:
  - tag
