kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  environment:
    EDITOR: vim
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  commands:
  - pip install --upgrade pip setuptools
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make testdeployment
  - make test

- name: x86_64-linux
  platform:
    os: linux
    arch: amd64
  image: python:3.7
  commands:
  - . cli/venv/bin/activate
  - make coverage
  - make release
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  when:
    event: tag

- name: publish
  image: plugins/github-release
  settings:
    api_key:
      from_secret: repo_api_key
    files: cli/dist/*
  when:
    event: tag

trigger:
  branch:
  - master
  - develop
  event:
  - push
  - tag

volumes:
- name: terraform
  host:
    path: /usr/local/bin/terraform
# kine: pipeline
# name: linux-cli-build

# platform:
#   os: linux
#   arch: amd64

# steps:
# - name: linux-cli-build
#   image: python:3.7-alpine
#   commands:
#   - cd cli
#   - pip install --upgrade pip setuptools
#   - pip install -r requirements.txt
#   - pip install -e .
#   - pyinstaller drone-deploy.spec --hidden-import=configparser
#   - 

# when:
#   branch:
#   - develop
