kind: pipeline
name: default

steps:
- name: test-x86_64-linux
  image: python:3.7
  environment:
    EDITOR: vim
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  commands:
  - pip install --upgrade pip setuptools
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make coverage

- name: release-x86_64-linux
  platform:
    os: linux
    arch: amd64
  image: python:3.7
  commands:
  - . cli/venv/bin/activate
  - make test
  - make release
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  when:
    event: tag

volumes:
- name: terraform
  host:
    path: /usr/local/bin/terraform


trigger:
  branch:
  - master
  event:
  - push
  - tag

---
# https://github.com/drone-runners/drone-runner-exec
kind: pipeline
type: exec
name: os-x

platform:
  os: darwin
  arch: amd64

steps:
- name: test-x86_64-osx
  image: python:3.7
  environment:
    EDITOR: vim
    PATH: /usr/local/opt/python/libexec/bin:$PATH
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  commands:
  - pip install --upgrade pip setuptools
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make coverage

- name: release-x86_64-osx
  image: python:3.7
  commands:
  - . cli/venv/bin/activate
  - make test
  - make release
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  when:
    event: tag


trigger:
  branch:
  - master
  - develop
  event:
  - push
  - tag
