kind: pipeline
name: default

steps:
- name: test-x86_64-linux
  image: python:3.7
  environment:
    EDITOR: vim
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  commands:
  - pip install --upgrade pip setuptools
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make coverage

- name: release-x86_64-linux
  platform:
    os: linux
    arch: amd64
  image: python:3.7
  commands:
  - env
  - . cli/venv/bin/activate
  - make test
  - make release
  volumes:
  - name: terraform
    path: /usr/local/bin/terraform
  when:
    event: tag

volumes:
- name: terraform
  host:
    path: /usr/local/bin/terraform


trigger:
  branch:
  - master
  - develop
  event:
  - push
  - tag

---
# https://github.com/drone-runners/drone-runner-exec
kind: pipeline
type: exec
name: os-x

platform:
  os: darwin
  arch: amd64

steps:
- name: test-x86_64-osx
  image: python:3.7
  environment:
    EDITOR: vim
    PATH: /usr/local/opt/python/libexec/bin:/usr/local/bin:$PATH
    GITHUB_API_TOKEN:
      from_secret: repo_api_key
  commands:
  # ensure homebrew and terraform are installed on runner mac and reinstall python because of bug:
  # https://discourse.brew.sh/t/pip-install-upgrade-pip-breaks-pip-when-installed-with-homebrew/5338
  - env
  - brew reinstall python
  - make virtualenv
  - make venv
  - . cli/venv/bin/activate
  - make
  - make test
  - make release

trigger:
  event:
  - tag
