### DEPLOYMENT CONFIG FILE #############################################
# The 'drone-deploy' cli app uses this file to configure terraform.
# Any of these values can be overidden by exporting a corresponding env
# var. E.g, export DRONE_AWS_REGION=us-east-2 overwrites drone_aws_region
#########################################################################
## WHERE TO DEPLOY
drone_aws_region: us-east-1
drone_vpc_id: ""


## ROUTE53 DOMAIN
# I.E., 'drone.yourdomain.com'
drone_server_host_name: drone
drone_server_hosted_zone: yourdomain.com


## DRONE SERVER INSTANCE SETTINGS
drone_server_key_pair_name: ""
drone_server_instance_type: t2.micro
drone_docker_compose_version: 1.24.0


## DRONE SERVER FIREWALL ACL'S (aws security groups)
# http and https must be open for drone server to get automatic TLS
# certs from lets encrypt. We should move to dns challenge instead 
# http/https challenge in the future if you want to lock down ports
# 80 and 443. You can always lock down the ports once the cert has
# been issued, and then again when it's time to renew.
# 0.0.0.0/0 == 'Allow all ip addresses.'
# /32 == 'one ip address'
drone_server_allow_http:
- 0.0.0.0/0
drone_server_allow_https:
- 0.0.0.0/0
drone_server_allow_ssh:
- your.public.ip.address/32
- another.admins.ip.address/32

# note: if you do not need ssh access to the drone-server, remove them


# DRONE SERVER REGISTRATION SETTINGS
drone_open: false
drone_admin: your_github_user_name
drone_user_filter:
- your_github_user_name
- another_github_user_name


# GITHUB OATH SETTINGS
drone_github_server: https://github.com
drone_github_client_id: 12345678903423
drone_github_client_secret: abcdefghijklmnopqrtub123555afd34134


# DRONE SETTINGS
drone_agents_enabled: true
drone_tls_autocert: false
drone_cli_version: 1.0.8
drone_server_docker_image: drone/drone:1


## THE SETTINGS BELOW ARE AUTOGENERATED
# The 'drone-server' cli will add/update the following settings, but they
# can be edited directly if needed.
drone_server_ami: ""
drone_deployment_id: ""
drone_builder_arn: ""
